export default {
  route: {
    monitoringAnalysis: '区域监测分析',
    businessApplication: '业务管理',
    InformationManagement: '信息管理',
    transactions: '上报重点可疑交易报告',
    reportList: '名单库管理',
    transactionReports: '重点可疑交易报告核对',
    reportVerification: '重点可疑交易报告核对管理',
    /** -----------------------------------------上面是新增的路由title名称------------------------ */
    home: '首页',
    permission: '权限测试页',
    pagePermission: '页面权限',
    directivePermission: '指令权限',
    icons: '图标',
    example: '综合实例',
    Table: 'Table',
    dynamicTable: '动态table',
    dragTable: '拖拽table',
    inlineEditTable: 'table内编辑',
    complexTable: '综合table',
    errorPages: '错误页面',
    page401: '401',
    page404: '404',
    errorLog: '错误日志',
    i18n: '国际化',
    /** -----------------------------------------通用路由title名称------------------------ */
    detail: '详情',
    notice: '通知公告',
    import: '导入',
    view: '查看',
    add: '新增',
    submitProfile: '报送概要',
    file: '文件列表',
    /** -----------------------------------------报送端路由title 名称--------------------- */
    // 业务管理
    businessManage: '跨境协查申请',
    businessManage_query: '查询',
    // 数据报送
    dataSubmit: '数据报送',
    onlineFill: '在线填报',
    pageLoading: '页面加载',
    newBigDeals: '大额新增',
    newDoubtfulDeals: '新增可疑',
    correctionBigDeals: '大额补正',
    fillWays: '选择填报方式',
    fillCheck: '查看',
    filePreview: '报文预览',
    notFound: '未报送',
    hadFound: '已报送',
    receipt: '回执管理',
    exception: '异常包管理',
    fill: '文件公函',
    zeroReport: '零报告管理',
    customSuspiciousTrade: '自定义可疑交易特征',
    entryManual: '自定义可疑交易手工录入',
    entryTool: '自定义可疑交易工具录入',
    importQuery: '导入查询结果',
    artificialCorrection: '人工补正',
    addReply: '文件公函回复',
    reply: '已回复',
    unReply: '未回复',
    case: '经典案例',
    train: '报送培训',
    download: '下载中心',
    question: '常见问题',
    bigDelete: '大额交易批量删除',

    // 定点监测
    fixedMonitor: '定点监测',
    sendMonitorTask: '上报监测任务',
    acceptMonitorTask: '接收监测任务',

    // 机构管理
    institutionManage: '机构管理',
    informationMaintenance: '报告机构信息维护',
    informationChange: '报告机构信息变更',
    quit: '报告机构退出申请',
    userManage: '机构网点管理',
    result: '机构网点导入结果查询',
    branchDetail: '机构网点导入查看详情',

    /** --------------------------------------------中心端路由title 名称 ---------------------*/

    // 数据报送
    dataReceive: '数据接收',
    suspiciousReport: '可疑报告标注',
    wrongManage: '异常包管理',
    originalMessage: '原始报文管理',
    dataBack: '报文追溯',
    // zeroReportManage: '零报告管理',
    customSuspiciousTradeDtetail: '自定义可疑交易特征详情',
    centerEntryManual: '自定义可以交易手工录入',

    // 上报研判线索
    judgedClues: '上报分析申请',
    submit: '查询',
    judgedCluesManage: '查询',
    analyze: '分析',
    analyzeManage: '业务员分析',
    judgedCluesStatistics: '统计',
    // 上报线索库
    reportClues: '上报线索库',
    reportCluesManage: '查询', // 上个版本（线索库管理）
    statistics: '统计', // 上个版本（线索信息统计）
    reportCluesImoport: '线索库管理批量导入',
    reportCluesHadle: '线索库管理手工录入',
    // 举报管理
    reportingManagement: '举报管理',
    warehousingPretreatment: '举报入库及预处理',
    informationProcessingFlow: '举报信息处理流转',
    inquiryDetailedDisplay: '举报查询及明细展示',
    informationStatistics: '举报信息统计',
    // 上报重点可疑交易报告
    reportEmphasisDoubtful: '上报重点可疑交易报告',
    reportEmphasisDoubtfulQuery: '查询',
    reportEmphasisDoubtfulStatistics: '统计',
    // 重点可疑交易报告核对
    emphasisDoubtful: '重点可疑交易报告核对',
    // 重点可疑交易报告核对管理
    suspiciousCheck: '重点可疑交易报告核对管理',
    suspiciousCheckQuery: '查询',
    // 数据生命周期管理
    dataCycle: '数据生命周期管理',
    dataCycleQuery: '数据迁移',
    dataCycleStatistics: '统计日志',
    // 线索分析专项申请
    analysisSpecial: '跨区域数据申请',
    analysisSpecialQuery: '查询',
    analysisSpecialStatistics: '统计',
    analysisSpecialApply: '申请单',

    // 线索库管理
    cueManage: '线索管理',
    investigation: '境内协查类文件管理',
    intelligence: '情报文件管理',
    interFileManage: '国际情报文件管理',
    analysis: '境内情报类文件管理',
    autonomousAnalysis: '自主分析',
    archives: '协查文件档案表',
    dataEntry: '数据录入管理',
    feedBack: '反馈信息管理',
    interIntelligence: '国际情报文件报中心领导',
    interFileTransfer: '国际情报文件移送通报',
    administration: '行政调查管理',
    backInformation: '反馈信息查询',
    backInformationTitle: '反馈信息管理',
    matchField: '匹配信息查询',
    matchFieldTitle: '匹配信息管理',
    // 人工补正
    info: '人工补正管理',
    statistical: '人工补正情况统计',

    // 机构能力建设
    institutionBuild: '机构能力建设',
    noticeAdd: '通知公告新建',
    officialDocumentsReceive: '接收公函',
    officialDocumentsSend: '发送公函',
    officialDocuments: '文件公函',

    // 机构管理
    accountManage: '机构账户管理',
    approval: '机构审批管理',
    informationManage: '机构信息管理',
    branchManage: '机构网点管理',
    passwordModifyRecord: '密码变更情况统计',

    // 名单预警
    rosterWarning: '名单预警',
    rosterManage: '名单管理',
    rosterManageBranch: '分支机构名单',
    levelConfiguration: '代码配置',
    rosterManageDeploy: '名单预警配置',
    rosterManageanalyst: '分析员关注名单',
    manualEntry: '手工录入',
    authorizationManage: '授权管理',
    addAuthorization: '新增授权',
    forewarningTask: '预警任务管理',
    advancedForewarningTask: '高级预警任务管理',
    newTask: '新增',
    forewarningRule: '预警规则管理',
    advancedForewarningRule: '高级预警规则管理',
    forewarningEnd: '预警结果管理',
    deploy: '名单预警配置',
    ruleModel: '简单规则模型',
    advancedWarnListDispos: '高级名单预警处理',
    // 任务管理
    taskManagement: '任务管理',
    advancedDistribution: '高级预警结果分发-分析处室',
    earlyWarningResults: '高级预警结果分发-分析员',
    modelWarningConfiguration: '模型预警配置', // 安小霞
    seniorListWarningConfiguration: '高级名单预警配置',
    rulesWarningConfiguration: '排名规则预警配置',
    suspiciousWarningConfiguration: '可疑交易报告预警配置',
    modelWarning: '模型预警', // 马黎健
    modelWarning_query: '模型预警查询',
    suspicious_warnings: '可疑交易报告预警',
    suspicious_warning: '可疑交易报告预警查询',
    advancedList_senior: '高级名单预警',
    advancedList_query: ' 高级名单预警查询',
    ruleWarning_rules: '排名规则预警',
    ruleWarning_query: '排名规则预警查询',
    // 可疑交易报告预警处理
    suspWarningDeal: '可疑交易报告预警处理',

    // 排名规则管理
    rankingRulesFather: '排名规则管理',
    rankingRules: '排名规则预警处理',
    rankingMainstayAdmin: '主体账户库参数管理',
    // 跨网单向传输
    center_fileTransfer: '跨网单向传输',
    center_fileTransfer_fileSend: '文件发送',
    center_fileTransfer_fileReceive: '文件接收',

    // 代码管理
    codeManagement: '代码管理',
    codeManagementBranch: '代码管理',
    basicsCode: '基础代码管理',
    businessParam: '业务参数管理',
    workdaySet: '工作日设定',
    organizationType: '报告机构类别管理',
    stateSwitch: '报送状态开关',
    statisticsCycle: '零报告统计周期',
    accountLock: '账户锁定管理',
    sendTime: '报送时限管理',
    rightDelete: '报告纠删限制管理',
    bigStandard: '大额标准限额',
    warningBack: '警告回执触发条件配置',
    commonParams: '公共参数管理',

    // 系统管理
    systemManage: '系统管理',
    updateLog: '系统更新日志',
    operationLog: '系统操作日志',
    operationLogManage: '系统更新日志管理',
    params: '系统参数管理',
    messageInterface: '消息接口',
    storeUpdate: '匹配信息存储更新',
    typeManage: '匹配信息类型管理',
    authorityManage: '反馈信息类型管理',
    definedData: '后端录入自定义数据类型',
    ruleConfiger: '预警规则配置',

    // 数据查询
    customResults: '定制结果',
    customResults2: '定制结果',
    dataQuery: '数据查询',
    templateManage: '模板管理',
    automaticQuery: '批量自动查询',
    personApproval: '敏感任务审批',
    workPlatform: '工作台',
    search: '全文检索',
    mergeView: '文本比较',
    intelligenceFile: '情报类文件查询',
    custom: '定制模板查询',
    resultList: '定制结果列表',
    executionRule: '规则执行',
    simpleRule: '简单规则',
    statisticForm: '统计报表',
    bigstatistic: '大额交易统计分析',
    payingOrgstatistic: '支付机构大额统计分析',
    suspiciousstatistic: '可疑交易统计分析',
    suspiciousdealmain: '按交易主体统计',
    suspiciousflow: '账户资金流向分析',
    suspiciousrate: '及时率统计',
    suspicioussequence: '报告时序分析',
    suspiciouscustom: '自定义统计分析',
    dataDown: '近、离线数据任务下载',
    // --------------------------------------------数据监测分析路由title 名称 ---------------------*/
    dataType: '特定数据类型查询',
    dataType2: '特定数据类型查询',
    sendTaskInfo: '分析任务分发',
    fenTaskInfo: '分析任务',
    sendTaskInfoAdd: '新建分析任务',
    searchTaskInfo: '查询',
    resultExport: '地方协查及结果导出',
    resultExportJian: '监测分析结果导出',
    fenResultExport: '地方协查及结果导出',
    fenResultExportJian: '监测分析结果导出',
    receiptQuery: '回执查询',
    // ---------- 数据处理 -------------
    dataHandl: '数据处理',
    dataHandlProject: '项目信息',
    projectProcedures: '项目处理流程',
    dataLifecycleL: '数据生命周期',
    processDispatch: '流程调度计划',
    processExecute: '流程执行信息',
    resultInfo: '结果信息',
    numTransfer: '编号移送',
    embedded: '嵌入外部网页',

    // ------- 动态主体 -----------
    modelPlatform: '模型平台(生产环境)',
    // 数据管控
    dataControl: '数据管控',
    // 数据管控下三级菜单
    dataModel: '数据模板管理',
    // dataManage: '模型数据管理',
    dataReady: '数据准备任务',
    establishDataInfo: '建模数据信息',
    // 模型管理
    modelManage: '模型管理',
    modelInfoData: '模型信息',
    modelInfoIndex: '模型信息',
    modelNewExperimental: '新建实验',
    modelSubmitAudit: '提交审核',
    BeginBulk: '模型数据集',
    availableDataList: '可用数据列表',
    // 模型审核
    modelAudit: '模型审核',
    // 模型监控
    modelPlatformMonitor: '模型监控',
    summarize: '概览',
    productionEnviron: '预测监控',
    runHistory: '运行历史',
    releaseList: '发布列表',
    // 模型预警处理
    warningProcessing: '模型预警处理',

    // modelList: '模型列表',
    // 模型库监测
    libraryMonitoring: '模型库监测',
    // ------------------------模型平台 集研环境--------------------------
    modelPlatformCR: '模型平台(集研环境)',
    modelInfoIndexCR: '模型信息(Sophon建模)',
    modelInfoDataCR: '模型管理',
    // ------------------------数据治理 ----------------
    dataGovernance: '数据治理',
    // ruleManage: '治理规则',
    ruleScanning: '规则扫描',
    rule: '规则配置',
    // ruleapproval: '规则审批',
    scanningMonitor: '扫描问题处理',
    scanningTask: '扫描问题历史记录',
    dataClean: '自动清理',
    cleanProgram: '清理方案管理',
    cleanAuto: '执行清理',
    cleanArtificial: '人工清理',
    cleanHistory: '清理历史记录',
    fixedPoint: '定点监测',
    extract: '抽取监测任务',
    receive: '接收监测任务',
    fpquery: '监测任务历史查询',
    // fpapproval: '监测任务审批',
    correctionapproval: '清理任务审批',
    artificialLaunch: '发起人工补正',
    artificialApproval: '补正任务审批',
    artificialNotice: '发送补正通知',
    artificialVerify: '补正结果核对',
    artificialHistory: '补正历史记录',
    dataSampling: '数据抽样',
    dataSamplinghistory: '抽样历史记录',
    qualityEvaluation: '数据质量评价',
    basicConfig: '基础配置(收集处)',
    evaluationOrgan: '评价机构模板配置',
    evaluationIndicator: '评价指标模板配置',
    evaluateStandard: '整合评价标准',
    crossbodyAlignment: '跨机构比对',
    comparingHistory: '比对历史记录',
    task: '评价任务管理（收集处）',
    evaluationResult: '查看评价结果（收集处）',
    thinIndicator: '接收评价任务（分析处）',
    indicatorEvaluation: '指标评价（分析处）',
    samplingEvaluation: '数据抽样评价',
    configIndicator: '配置评价指标',
    randomSampling: '随机抽样评价',
    samplingResult: '查看抽样评价结果',
    dataAuthority: '数据权限管理',
    permissionApply: '权限申请',
    interregionalNotice: '详情',
    interregionalFirsttrial: '跨区初审',
    permissionApprover: '权限审批',
    interregionalApprover: '跨区审批',

    // -----------------------统计报表------------------
    fixedStatements: '固定报表',
    statisticAnalysis: '统计分析',
    antimoneyAuthority: '统计分析',
    // reportForm: '统计报表',
    dashboard: '仪表盘',
    // -----------------------知识库论坛------------------
    knowledgeBaseForum: '知识库论坛',
    knowledgeDatabase: '知识资料库',
    businessExchangeForum: '业务交流论坛',
    // -----------------------宏观分析------------------
    macroAnalysis: '宏观分析',
    SelfHelpAnalysis: '自助分析',
    intelligentAnalyze: '智能分析',
    reportManage: '宏观分析报告管理',
    stateManage: '报表管理',
    stateView: '报表查看',
    messageCheck: '报文校验规则',
    messageRule: '报文规则',
    ruleTemplate: '规则模板',
    // ----------------  国际 ---------------
    inter_fileTransfer: '文件传输',
    inter_inbox: '收件箱',
    inter_outbox: '发件箱',
    inter_draftbox: '草稿箱',
    inter_dustbin: '垃圾箱',
    inter_approval: '审批流程',
    inter_workPlatform: '任务工作台',
    inland_matchInformation: '文件传输',
    inland_matchInformation_transfer: '国内信息传输',
    inland_matchInformation_receive: '国内信息接收',
    inland_matchInformation_pigeonhole: '文件归档',
    inland_matchInformation_atuoSend: '信息自动发送设置',
    conjointAnalysis: '联合分析',
    conjointAnalysisBranch: '创建联合分析（分支）', // 仅为演示用
    conjointAnalysisAdd: '创建联合分析（中心）',
    conjointAnalysisList: '联合分析',
    conjointAnalysisStatistics: '统计',
    inland_inlandSystemManage: '系统管理',
    nodeManage: '传输控制节点管理',
    filterRole: '文件传输过滤规则',
    administrationCollect: '行政调查数据收集',
    collectDataUpload: '数据上传',
    collectQuery: '查询',
    collectStatistics: '统计'
  },

  login: {
    title: 'Login Form',
    logIn: 'Log in',
    username: 'Username',
    password: 'Password',
    any: 'any',
    thirdparty: 'Or connect with',
    thirdpartyTips:
      'Can not be simulated on local, so please combine you own business simulation! ! !'
  },
  navbar: {
    logOut: '退出系统',
    title: '中国反洗钱监测分析系统'
  },
  message: {
    index: '序号'
  }
}
